// <auto-generated />
using System;
using Macs.WebApi.DataAccess.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Macs.WebApi.DataAccess.Migrations
{
    [DbContext(typeof(MacsContext))]
    partial class MacsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Macs.WebApi.DataAccess.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Preferred")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("43097261-61bb-4cc7-8515-567b1f1e4f20"),
                            AddressLine1 = "Heriot-Watt University",
                            AddressLine2 = "",
                            AddressLine3 = "",
                            City = "Edinburgh",
                            Country = "Scotland",
                            IsActive = true,
                            PersonId = new Guid("959d7bf9-51f9-4a70-9f35-8fa82e06c718"),
                            PostCode = " EH14 4AS",
                            Preferred = true,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("847c1f1a-17f7-44c6-a3b9-ccf24b9bc728"),
                            AddressLine1 = "Heriot-Watt University",
                            AddressLine2 = "",
                            AddressLine3 = "",
                            City = "Edinburgh",
                            Country = "Scotland",
                            IsActive = true,
                            PersonId = new Guid("a3442178-b1ab-4ed6-92f3-24888c5aca1c"),
                            PostCode = " EH14 4AS",
                            Preferred = true,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("7cb0b701-13de-4453-85c3-e0954268de2d"),
                            AddressLine1 = "Heriot-Watt University",
                            AddressLine2 = "",
                            AddressLine3 = "",
                            City = "Edinburgh",
                            Country = "Scotland",
                            IsActive = true,
                            PersonId = new Guid("1d85075e-ce29-4c91-9e68-5fc11422e233"),
                            PostCode = " EH14 4AS",
                            Preferred = true,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("4444210e-fc70-4771-915e-91068ada5343"),
                            AddressLine1 = "Heriot-Watt University",
                            AddressLine2 = "",
                            AddressLine3 = "",
                            City = "Edinburgh",
                            Country = "Scotland",
                            IsActive = true,
                            PersonId = new Guid("c67b71b0-a5c4-4f90-909a-90894a5548ca"),
                            PostCode = " EH14 4AS",
                            Preferred = true,
                            Type = 2
                        });
                });

            modelBuilder.Entity("Macs.WebApi.DataAccess.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Preferred")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd0c784d-a0cc-4258-9b84-31ecf7c94b7e"),
                            IsActive = true,
                            PersonId = new Guid("959d7bf9-51f9-4a70-9f35-8fa82e06c718"),
                            Preferred = true,
                            Type = 1,
                            Value = "mirela@hw.com"
                        },
                        new
                        {
                            Id = new Guid("5294c467-af24-4831-a941-ee7493854556"),
                            IsActive = true,
                            PersonId = new Guid("a3442178-b1ab-4ed6-92f3-24888c5aca1c"),
                            Preferred = true,
                            Type = 1,
                            Value = "nastia@hw.com"
                        },
                        new
                        {
                            Id = new Guid("762e3689-8e3c-47ef-a49c-1d0821430411"),
                            IsActive = true,
                            PersonId = new Guid("1d85075e-ce29-4c91-9e68-5fc11422e233"),
                            Preferred = true,
                            Type = 1,
                            Value = "paul@hw.com"
                        },
                        new
                        {
                            Id = new Guid("c8fcf62e-99c2-401b-a86e-d921021d8139"),
                            IsActive = true,
                            PersonId = new Guid("c67b71b0-a5c4-4f90-909a-90894a5548ca"),
                            Preferred = true,
                            Type = 1,
                            Value = "john@hw.com"
                        });
                });

            modelBuilder.Entity("Macs.WebApi.DataAccess.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = new Guid("959d7bf9-51f9-4a70-9f35-8fa82e06c718"),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mirela",
                            LastName = "Developer",
                            MiddleName = "",
                            Title = "Ms"
                        },
                        new
                        {
                            Id = new Guid("a3442178-b1ab-4ed6-92f3-24888c5aca1c"),
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nastia",
                            LastName = "Developer",
                            MiddleName = "",
                            Title = "Miss"
                        },
                        new
                        {
                            Id = new Guid("1d85075e-ce29-4c91-9e68-5fc11422e233"),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Paul",
                            LastName = "Developer",
                            MiddleName = "",
                            Title = "Mr"
                        },
                        new
                        {
                            Id = new Guid("c67b71b0-a5c4-4f90-909a-90894a5548ca"),
                            DateOfBirth = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Developer",
                            MiddleName = "",
                            Title = "Mr"
                        });
                });

            modelBuilder.Entity("Macs.WebApi.DataAccess.Entities.Address", b =>
                {
                    b.HasOne("Macs.WebApi.DataAccess.Entities.Person", null)
                        .WithMany("Addresses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Macs.WebApi.DataAccess.Entities.Contact", b =>
                {
                    b.HasOne("Macs.WebApi.DataAccess.Entities.Person", null)
                        .WithMany("Contacts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Macs.WebApi.DataAccess.Entities.Person", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
